- name: eq
  args:
    - name: expression1
      type: resolvesToExpression
    - name: expression2
      type: resolvesToExpression
- name: ne
  args:
    - name: expression1
      type: resolvesToExpression
    - name: expression2
      type: resolvesToExpression
- name: filter
  usesNamedArgs: true
  args:
    - name: input
      type: resolvesToArrayExpression
    - name: cond
      type: resolvesToBoolExpression
    - name: as
      type: string
      isOptional: true
    - name: limit
      type: resolvesToNumberExpression
      isOptional: true
