---
- name: match
  args:
    - name: matchExpr
      type: resolvesToMatchExpression

- name: sort
  args:
    - name: sortSpecification
      type: resolvesToSortSpecification

- name: limit
  args:
    - name: limit
      type: int
