---
- name: match
  className: MatchStage
  args:
    - name: matchExpr
      type: resolvesToMatchExpression

- name: sort
  args:
    - name: sortSpecificataion
      type: resolvesToSortSpecification

- name: limit
  args:
    - name: limit
      type: int
