  - name: test-rhel80-php-%phpVersion%-local-lowest
    tags: ["test", "rhel", "x64", "php%phpVersion%", "pr", "tag"]
    display_name: "Test: RHEL 8.0, PHP %phpVersion%, Lowest Dependencies"
    run_on: rhel80-small
    expansions:
      FETCH_BUILD_VARIANT: "build-rhel80"
      FETCH_BUILD_TASK: "build-php-%phpVersion%-lowest"
      PHP_VERSION: "%phpVersion%"
      DEPENDENCIES: "lowest"
    depends_on:
      - variant: "build-rhel80"
        name: "build-php-%phpVersion%-lowest"
    tasks:
      - ".replicaset .local .4.0 !.csfle"
